### ISSUE TITLE
[BUG] Minihack does not work with NLE v0.9.0

### ISSUE THREAD

**Issue by ngoodger** [facebookresearch/minihack#64]
## 🐛 Bug

Minihack does not work with NLE v0.9.0

## To Reproduce

Follow the Trying Out MiniHack example

```
[/usr/local/lib/python3.7/dist-packages/minihack/base.py](https://localhost:8080/#) in _patch_nhdat(self, des_file)
    366         """
    367         if not des_file.endswith(".des"):
--> 368             fpath = os.path.join(self.env._vardir, "mylevel.des")
    369             # If the des-file is passed as a string
    370             with open(fpath, "w") as f:

AttributeError: 'MiniHackRiver' object has no attribute 'env'
```

**Comment by ka00ri** [comment]
I encountered the same bug and downgraded nle to version 0.8.1.
